version: '3.3'

services:
  nginx:
    env_file:
      - .env
      - .build_env

  api:
    build:
      context: ./api-service
      dockerfile: Dockerfile.build
      args:
        VERSION: 0.0.1-SNAPSHOT
    env_file:
      - .env
      - .build_env

  ui:
    build:
      context: ./ui-service
      dockerfile: Dockerfile.build
      args:
        PUBLIC_URL: /ui
    env_file:
      - .env
      - .build_env

  schema:
    build:
      context: ./schema-service
      dockerfile: Dockerfile.build
    env_file:
      - .env
      - .build_env

  db:
    env_file:
      - .env
      - .build_env

  adminer:
    env_file:
      - .env
      - .build_env
